######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 17 04:28:30 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lgmpxx
QMAKE_CXXFLAGS += -std=c++0x -W -Wall -Wextra -pedantic

# Input
HEADERS += encapp.hpp
FORMS += encapp.ui
SOURCES += encapp.cpp main.cpp
